const APP_VERSION='3.0.0';
const STORAGE_KEY='mi-pauta-lorazepam-v2';
const DB_NAME='mi-pauta-db';
const DB_STORE='state';
const DB_KEY='main';
let state=null,toastTimer=null,doseMode='mg',selectedCraving=2,ticker=null;
const $=id=>document.getElementById(id);

function initialState(){return MedCore.normalizeState({version:APP_VERSION,schemaVersion:3,logs:[],cravings:[],tabletMg:null,updatedAt:Date.now(),lastBackupAt:null});}
async function loadState(){let local=null,indexed=null;try{local=JSON.parse(localStorage.getItem(STORAGE_KEY));}catch{}try{indexed=await idbRead();}catch{}const candidates=[local,indexed].filter(Boolean).map(x=>MedCore.normalizeState(x));state=candidates.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0))[0]||initialState();await persistState(false);}
async function persistState(renderAfter=true){state.version=APP_VERSION;state.schemaVersion=3;state.updatedAt=Date.now();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));try{await idbWrite(state);}catch{}if(renderAfter)render();}
function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function idbWrite(value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(value,DB_KEY);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(tx.error);};});}
async function idbRead(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readonly');const req=tx.objectStore(DB_STORE).get(DB_KEY);req.onsuccess=()=>{db.close();resolve(req.result||null);};req.onerror=()=>{db.close();reject(req.error);};});}
function fmtMg(v){const n=Math.round((Number(v)+Number.EPSILON)*100)/100;return `${Number.isInteger(n)?n:n.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')} mg`;}
function fmtDateTime(v){if(!v)return'—';return new Intl.DateTimeFormat('es-ES',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v));}
function fmtDuration(ms,short=false){if(ms==null)return'—';let s=Math.max(0,Math.floor(ms/1000));const days=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);if(short)return days?`${days} d ${h} h`:h?`${h} h ${m} min`:`${m} min`;return{days,h,m,s:s%60};}
function localInput(date=new Date()){const p=n=>String(n).padStart(2,'0');return`${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`;}
function nowZone(){try{return Intl.DateTimeFormat().resolvedOptions().timeZone||null;}catch{return null;}}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200);}
function show(id){$(id).showModal();}function close(id){$(id).close();}
function render(){const now=new Date();$('todayLabel').textContent=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}).format(now);const hasDose=!!MedCore.lastDose(state.logs,now);$('setupCard').classList.toggle('hidden',hasDose);$('activeApp').classList.toggle('hidden',!hasDose);$('defaultTabletMgInput').value=state.tabletMg||'';renderLive();renderCharts();renderIntervals();renderHistory();renderCraving();renderBackup();}
function renderLive(){const now=new Date(),last=MedCore.lastDose(state.logs,now);if(!last)return;const dur=fmtDuration(MedCore.currentAbstinenceMs(state.logs,now));$('counter').innerHTML=`<strong>${dur.days}</strong><span>d</span><strong>${String(dur.h).padStart(2,'0')}</strong><span>h</span><strong>${String(dur.m).padStart(2,'0')}</strong><span>min</span><strong>${String(dur.s).padStart(2,'0')}</strong><span>s</span>`;$('lastDoseText').textContent=`Contando desde ${fmtDateTime(last.at)} · ${fmtMg(last.amountMg)}`;$('lastDoseValue').textContent=fmtDateTime(last.at);$('recordValue').textContent=fmtDuration(MedCore.recordAbstinenceMs(state.logs,now),true);$('mg7').textContent=fmtMg(MedCore.totalMgWithin(state.logs,7,now));$('mg30').textContent=fmtMg(MedCore.totalMgWithin(state.logs,30,now));$('rescueCount').textContent=MedCore.recentDoseCount(state.logs,7,now);const tr=MedCore.consumptionTrend(state.logs,7,now);$('trendValue').textContent=tr.direction==='down'?'↓ Bajando':tr.direction==='up'?'↑ Subiendo':'→ Estable';const exp=MedCore.estimateExposure(state.logs,now);$('exposureLabel').textContent=exp.label;$('exposureOrb').className=`exposure-orb level-${exp.level}`;$('exposureCopy').textContent=`${fmtDuration((exp.inputs.hoursSinceLastDose??0)*3600000,true)} desde la última dosis · ${fmtMg(exp.inputs.mg7)} en 7 días.`;[...$('levelTrack').children].forEach((el,i)=>el.classList.toggle('active',i<exp.level));}
function renderCharts(){const data=MedCore.dailyDoseBuckets(state.logs,14,new Date(),nowZone());const max=Math.max(1,...data.map(x=>x.mg));const box=$('doseChart');box.innerHTML='';data.forEach(x=>{const col=document.createElement('div');col.className='bar-col';const h=Math.max(3,Math.round(x.mg/max*118));col.innerHTML=`<div class="bar-value">${x.mg?x.mg:''}</div><div class="bar-fill" style="height:${h}px"></div><span>${Number(x.date.slice(-2))}</span>`;box.appendChild(col);});}
function renderIntervals(){const list=$('intervalList'),arr=MedCore.doseIntervals(state.logs,new Date()).slice(-6).reverse();$('intervalCount').textContent=`${arr.length} ${arr.length===1?'intervalo':'intervalos'}`;list.innerHTML='';if(!arr.length){list.innerHTML='<p class="empty">Aún no hay dos dosis entre las que calcular un intervalo.</p>';return;}arr.forEach((x,i)=>{const row=document.createElement('div');row.className='interval-row';row.innerHTML=`<span>${i===0?'Último':'Anterior'}</span><strong>${fmtDuration(x.ms,true)}</strong><small>${fmtDateTime(x.from.at)} → ${fmtDateTime(x.to.at)}</small>`;list.appendChild(row);});}
function renderCraving(){const data=MedCore.cravingBuckets(state.cravings,14,new Date(),nowZone()),box=$('cravingChart');box.innerHTML='';data.forEach(x=>{const el=document.createElement('div');el.className='craving-col';const h=x.level?Math.round(x.level/4*90):3;el.innerHTML=`<div class="craving-fill ${x.level?'':'emptybar'}" style="height:${h}px"></div><span>${Number(x.date.slice(-2))}</span>`;box.appendChild(el);});}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function renderHistory(){const items=[...state.logs.filter(x=>x.drug==='lorazepam'),...state.cravings].sort((a,b)=>new Date(b.at)-new Date(a.at));const box=$('historyList');box.innerHTML='';if(!items.length){box.innerHTML='<p class="empty">No hay registros.</p>';return;}items.forEach(x=>{const dose=x.type!=='craving';const row=document.createElement('div');row.className='history-row';row.innerHTML=`<div class="history-icon ${dose?'dose':'crave'}">${dose?'L':'C'}</div><div class="history-main"><strong>${dose?fmtMg(x.amountMg):['','Bajo','Medio','Alto','Muy alto'][x.level]}</strong><span>${fmtDateTime(x.at)}${x.note?` · ${escapeHtml(x.note)}`:''}</span></div><div class="history-actions">${dose?`<button data-edit="${x.id}">Editar</button>`:''}<button data-delete="${x.id}" data-kind="${dose?'dose':'craving'}">Borrar</button></div>`;box.appendChild(row);});box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditDose(b.dataset.edit));box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deleteHistory(b.dataset.delete,b.dataset.kind));}
function renderBackup(){const b=$('quickBackupButton');if(!state.lastBackupAt)b.textContent='Guardar copia';else b.textContent=(Date.now()-state.lastBackupAt)>7*86400000?'Copia recomendada':'Copia guardada ✓';}
function openDose(id=null){doseMode='mg';document.querySelectorAll('[data-dose-mode]').forEach(b=>b.classList.toggle('active',b.dataset.doseMode==='mg'));$('mgField').classList.remove('hidden');$('tabletFields').classList.add('hidden');$('editDoseId').value=id||'';$('doseSheetTitle').textContent=id?'Editar dosis':'Registrar dosis';$('doseAmountInput').value='';$('tabletCountInput').value='';$('tabletMgInput').value=state.tabletMg||'';$('doseTimeInput').value=localInput();$('doseNoteInput').value='';show('doseSheet');}
function openEditDose(id){const log=state.logs.find(x=>x.id===id);if(!log)return;openDose(id);$('doseAmountInput').value=log.amountMg;$('doseTimeInput').value=localInput(new Date(log.at));$('doseNoteInput').value=log.note||'';}
async function saveDose(){const at=new Date($('doseTimeInput').value);if(Number.isNaN(at.getTime())||at>Date.now()+60000)return toast('Fecha u hora no válidas');let amount,tabletCount=null,tabletMg=null;if(doseMode==='tablets'){tabletCount=Number($('tabletCountInput').value);tabletMg=Number($('tabletMgInput').value);if(!(tabletCount>0)||!(tabletMg>0))return toast('Completa comprimidos y mg');amount=tabletCount*tabletMg;state.tabletMg=tabletMg;}else amount=Number($('doseAmountInput').value);if(!(amount>0))return toast('Introduce una cantidad válida');const id=$('editDoseId').value;const rec=MedCore.createDoseRecord({amountMg:amount,tabletCount,tabletMg,at,timeZone:nowZone(),offsetMinutes:-at.getTimezoneOffset(),note:$('doseNoteInput').value.trim()});if(id){const old=state.logs.find(x=>x.id===id);rec.id=id;state.logs=state.logs.map(x=>x.id===id?{...old,...rec}:x);}else state.logs.push(rec);await persistState();close('doseSheet');toast(id?'Dosis actualizada':'Dosis registrada');}
async function deleteHistory(id,kind){if(!confirm('¿Borrar este registro? Las estadísticas se recalcularán automáticamente.'))return;if(kind==='dose')state.logs=MedCore.deleteEntry(state.logs,id);else state.cravings=MedCore.deleteEntry(state.cravings,id);await persistState();toast('Registro borrado');}
function openCraving(){selectedCraving=2;[...$('cravingOptions').children].forEach(b=>b.classList.toggle('active',Number(b.dataset.level)===2));$('cravingTimeInput').value=localInput();$('cravingNoteInput').value='';show('cravingSheet');}
async function saveCraving(){const at=new Date($('cravingTimeInput').value);if(Number.isNaN(at.getTime())||at>Date.now()+60000)return toast('Fecha u hora no válidas');state.cravings.push(MedCore.createCravingRecord({level:selectedCraving,at,timeZone:nowZone(),offsetMinutes:-at.getTimezoneOffset(),note:$('cravingNoteInput').value.trim()}));await persistState();close('cravingSheet');toast('Craving registrado sin reiniciar el contador');}
async function exportBackup(){const payload={app:'Mi progreso lorazepam',version:APP_VERSION,exportedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const file=new File([blob],`lorazepam-backup-${MedCore.tzDateParts(new Date(),nowZone())}.json`,{type:'application/json'});try{if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:'Copia de seguridad'});else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}state.lastBackupAt=Date.now();await persistState();toast('Copia preparada');}catch(e){if(e?.name!=='AbortError')toast('No se pudo crear la copia');}}
async function importBackup(file){try{const parsed=JSON.parse(await file.text());const incoming=MedCore.normalizeState(parsed.state||parsed);if(!confirm('Esto sustituirá los datos actuales. ¿Continuar?'))return;state=incoming;await persistState();toast('Copia restaurada');}catch{toast('La copia no es válida');}}
function bind(){$('settingsButton').onclick=()=>show('settingsSheet');$('setupDoseButton').onclick=()=>openDose();$('logDoseButton').onclick=()=>openDose();$('logCravingButton').onclick=openCraving;$('saveDoseButton').onclick=saveDose;$('saveCravingButton').onclick=saveCraving;$('openHistoryButton').onclick=()=>{renderHistory();show('historySheet');};$('exposureInfoButton').onclick=()=>show('exposureInfoSheet');$('quickBackupButton').onclick=exportBackup;$('exportButton').onclick=exportBackup;$('importButton').onclick=()=>$('importFileInput').click();$('importFileInput').onchange=e=>{if(e.target.files?.[0])importBackup(e.target.files[0]);e.target.value='';};$('saveTabletMgButton').onclick=async()=>{const v=Number($('defaultTabletMgInput').value);state.tabletMg=v>0?v:null;await persistState();toast('Equivalencia guardada');};$('resetButton').onclick=async()=>{if(!confirm('Se borrarán dosis, craving e historial local. ¿Seguro?'))return;state=initialState();await persistState();toast('Datos borrados');};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close();}));document.querySelectorAll('[data-dose-mode]').forEach(b=>b.onclick=()=>{doseMode=b.dataset.doseMode;document.querySelectorAll('[data-dose-mode]').forEach(x=>x.classList.toggle('active',x===b));$('mgField').classList.toggle('hidden',doseMode!=='mg');$('tabletFields').classList.toggle('hidden',doseMode!=='tablets');});[...$('cravingOptions').children].forEach(b=>b.onclick=()=>{selectedCraving=Number(b.dataset.level);[...$('cravingOptions').children].forEach(x=>x.classList.toggle('active',x===b));});}
async function boot(){await loadState();bind();render();clearInterval(ticker);ticker=setInterval(()=>{if(state&&MedCore.lastDose(state.logs,new Date()))renderLive();},1000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=3.0.0').catch(()=>{});}
boot();
